version: "3"
services:
  node:
    container_name: nodeapp
    restart: always
    build: ./app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules # This will mount the node_modules directory to the host machine using the buildtime directory.
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - nodeapp-network

  mongodb:
    container_name: nodeapp-mongodb
    image: mongo
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network

  nginx:
    container_name: nodeapp-nginx-proxy
    restart: always
    build: ./nginx
    volumes:
      - ./nginx/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - node 
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
