version: "3"
services:
  node:
    container_name: nodeapp
    restart: always
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # This will mount the node_modules directory to the host machine using the buildtime directory.
    ports:
      - "5000:5000"
    depends_on: 
      - mongodb
    networks:
      - nodeapp-network

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
